---
language: node_js
node_js:
  - "5"
compiler: clang-3.6
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm config set progress false"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
